### ISSUE TITLE
[contract v2] [mobile] Scroll bar bug

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#1690]
**Describe the bug**
Mobile only: On modals with sufficient vertical length, a scroll bar appears on the right side. At the far right edge of the window, there's a thin black outline of the scroll bar which moves as I scroll up and down the page. Should be invisible.

**To Reproduce**
Open any modal long enough so the user has to scroll, like the filters on the marketplace or the EDIT PROFILE modal in the user profile.

**Expected behavior**
No scroll bar!

**Screenshots**
![813690fa-8a8d-43e0-ac48-f41bafc4a5b7](https://github.com/KlimaDAO/klimadao/assets/128430614/11f4c594-fc67-4fc0-8e3d-15b4146b6476)

**Smartphone (please complete the following information):**
 - OS: Android 12
 - Browser: MetaMask browser

**Comment by jabby09** [comment]
@0xtapi can you please retest this one?

**Comment by 0xtapi** [comment]
Scrollbar is gone on Chrome. On Firefox, it's a small gray bar. Both methods are fine.

The original issue was that the bar was half-hidden behind the modal, so it just looked broken. This issue is fixed ✅.

As to whether Chrome's or Firefox's implementation is better... I don't know. Both look fine to me 🤷.

**Comment by Atmosfearful** [comment]
I still see it on chrome on production. The issue is that we are using `webkit-scrollbar` which is non standard according to MDN
they advise avoiding it in production

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

![image](https://github.com/KlimaDAO/klimadao/assets/88635679/eaa1cc57-c7d5-4d0e-a971-463f5a6dbf57)

@0xMakka can you try adding 
`outline-offset: -1px` to `::-webkit-scrollbar-thumb` this fixed it in my dev tools at least. 
![image](https://github.com/KlimaDAO/klimadao/assets/88635679/70525e50-ba34-459a-8014-03d0fde80789)
