### ISSUE TITLE
[Website] Padding Issue for German on Mobile

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#351]
The German version of the website has a padding issue on (at least) Chrome and Brave. This doesn't happen with French.

Brave:
![Screenshot_20220427-200035_Brave](https://user-images.githubusercontent.com/99001851/165591303-bc1ff84d-0853-4e3b-b653-c2335a220017.jpg)

Chrome:
![Screenshot_20220427-110738_Chrome](https://user-images.githubusercontent.com/99001851/165591419-60937389-f276-4465-9fbb-5ad366421feb.jpg)

**Comment by Atmosfearful** [comment]
There must be a long string somewhere pushing the div wide. Can likely be fixed with a word wrap or flex wrap...

**Comment by ShimonD-KlimaDAO** [comment]
This is still an issue.

German:
![Screenshot_20220428-142325_Chrome](https://user-images.githubusercontent.com/99001851/165848309-93e8910b-fc31-4e64-ba85-59190d7c11e7.jpg)

French:
![Screenshot_20220428-142330_Chrome](https://user-images.githubusercontent.com/99001851/165848342-f304bf5b-8bb5-4e96-9e4b-f12be7a2ff66.jpg)

**Comment by Atmosfearful** [comment]
I'm pretty sure we fixed this, but can you double check for me please @ShimonD-KlimaDAO
